#!/bin/bash

su app <<EOSU
/var/www/html/bin/magento setup:install --base-url=magento2.local --backend-frontname=admin --language=en_US --timezone=Asia/Dubai --currency=AED --db-host=127.0.0.1 --db-name=magento --db-user=magento --db-password=magento --use-secure=1 --base-url-secure=https://magento2.local --use-secure-admin=1 --admin-firstname=Ahmed --admin-lastname=Allam --admin-email=demo@admin.com --admin-user=admin --admin-password=Admin@123
EOSU